export const visualScreenshotBudgets = {
  'ai-worker-checking-screen.png': 3500,
  'ai-worker-sign-in-required-screen.png': 3500,
  'ai-worker-unavailable-screen.png': 2500,
  'first-launch-screen.png': 4000,
  'original-cv-active-screen.png': 12_000,
  'original-cv-import-error-screen.png': 5500,
  'original-cv-replace-screen.png': 5000,
  'settings-ai-screen.png': 6000,
  'settings-ambient-activity-screen.png': 18_000,
  'settings-local-data-screen.png': 10_000,
  'workspace-active-adapted-cv-screen.png': 24_000,
  'workspace-active-cover-letter-screen.png': 24_000,
  'workspace-application-error-banner-screen.png': 25_000,
  'workspace-discard-draft-dialog.png': 1500,
  'workspace-editable-draft-screen.png': 10_000,
  'workspace-empty-screen.png': 8000,
  'workspace-generation-overlay-screen.png': 16_000,
  'workspace-multipage-preview-page-2.png': 10_000,
  'workspace-reviewed-draft-screen.png': 12_000,
  'workspace-review-error-screen.png': 10_000,
  'workspace-saved-job-delete-dialog.png': 1500,
  'workspace-settings-reset-dialog.png': 1500,
} as const
